### ISSUE TITLE
Simple but useful improvement

### ISSUE THREAD

**Issue by wolfcall** [er1/s228#9]
If you can add the following code to allow a small reference to be available regardless of where we are on the screen.
    `html<div id="items" style="background-color:red;width:300;position: fixed; top: 30%; 
right: 20px">
        555: Timer</br>
        7404: NOT</br>
        7408: AND</br>
        7432: OR</br>
        7442: Decoder</br>
        74164: Shift Register</br>
        74173: 4 Bit Register</br>
        74175: 4 bit Flip-Flop</br>
        74283: 4 bit adder</br>
    </div>`

It might need a little tune up but mostly this is the idea. If I can finish the tune up I will resubmit but this gives you the idea. If we have this while working on a lab it will reduce the amount of scrolling we have to do while working on labs. At least in just keeping track of what chip is what. and allow us to understand better where we are connecting.

Georges Mathieu
6863477

**Comment by er1** [comment]
It is outside the scope of markdown to do something like that and its kinda hackish.

You can use this code snippet if it helps. Copy and paste it into the address bar

```
javascript:document.body.innerHTML+='<dl style="background-color:red;width:300;position:fixed;top:30%;right:20px"><li>555: Timer</li><li>7404: NOT</li><li>7408: AND</li><li>7432: OR</li><li>7442: Decoder</li><li>74164: Shift Register</li><li>74173: 4 Bit Register</li><li>74175: 4 bit Flip-Flop</li><li>74283: 4 bit adder</li></dl>';undefined
```
